### ISSUE TITLE
Complete Nord theme

### ISSUE THREAD

**Issue by lusignan** [alletsee/rstudio-theme-collection#3]
Hi, I've made a port of the Nord theme for RStudio. In addition to the syntax highlighting this RStheme reskins all UI elements in accordance to the Nord palette. [Complete Nord theme](https://github.com/lusignan/Nord-RStudio)

**Comment by max-alletsee** [comment]
Hi Zac,
Thanks for creating your theme and for suggesting to add the theme. I have added it yesterday to the list.
(I noticed that there are several ports of the Nord theme and was wondering about the differences between them. I had also started to work on one, but I think some ports of other people are better, without being able to explain why... If I have a lot of free time, I might do a comparison.)
