### ISSUE TITLE
Themes Preview

### ISSUE THREAD

**Issue by GitHunter0** [alletsee/rstudio-theme-collection#4]
Hi, very cool project!

Is there a way to preview all the themes? Because it would be impractical to install and test one by one...

I'm specifically looking for some very similar to Idle Fingers but with just a few tweaks.

Thank you

**Comment by max-alletsee** [comment]
Hi,

Thanks for the suggestion. Do you have an idea of the structure of the preview?
The list of themes is already quite long, I'm not sure if adding screenshots in the main document will make it too difficult to navigate. Do you have any idea regarding this, just from a UI/UX perspective?

**Comment by GitHunter0** [comment]
Hey, thank you for the feedback.
You are right, so I believe the most feasible/simple way would be to have a command to install them all and then the user would be able to preview them inside RStudio (Global options -> Appearance) 
That is the approach of this package https://github.com/gadenbuie/rsthemes

**Comment by max-alletsee** [comment]
Thanks for the suggestion. This indeed might be fairly easy to implement once I find the time to do it.

**Comment by GitHunter0** [comment]
Nice @max-alletsee , it would be cool to test all the themes you collected

**Comment by max-alletsee** [comment]
Hi @GitHunter0 ,
with the newest version that I have uploaded just now, this should be possible. Moreover, I have added screenshots wherever they have been provided by the person that created the theme: You can find them as links in the list.

**Comment by GitHunter0** [comment]
Hey @max-alletsee , great news, I will take a look. Thank you
